### ISSUE TITLE
Start and End position joint_name mismatch

### ISSUE THREAD

**Issue by hustfzt2** [ros-industrial/motoman#128]
```
rosrun motoman_driver move_to_joint.py "[position]"

[ERROR] Start and End position joint_name mismatch

[ERROR] [WallTime: 1414508621.823816] Unable to move to commanded position. Aborting.
Traceback (most recent call last):
  File "/home/ubuntu/tsbb11/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 133, in <module>
    main(sys.argv[1:])
  File "/home/ubuntu/tsbb11/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 127, in main
    move_to_joint(end_pos, duration)
  File "/home/ubuntu/tsbb11/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 69, in move_to_joint
    traj = build_traj(get_cur_pos(), end_pos, duration)
  File "/home/ubuntu/tsbb11/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 47, in get_cur_pos
    return rospy.wait_for_message("joint_states", JointState, 5.0)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/client.py", line 408, in wait_for_message
    raise rospy.exceptions.ROSException("timeout exceeded while waiting for message on topic %s"%topic)
rospy.exceptions.ROSException: timeout exceeded while waiting for message on topic joint_states
```

I want to use ros to move the robot by using this according to the tutorial.

Could anyone help with those?

**Comment by gavanderhoorn** [comment]
@hustfzt2: can you give us some more information on your setup? Robot, ROS version, controller, how did you install everything?

**Comment by gavanderhoorn** [comment]
Closing because of inactivity.

@hustfzt2: please provide us with more information, otherwise we can't help you.

If you've solved the issue in the meanwhile, that would also be nice to know.
