### ISSUE TITLE
SIA20d MoveIt package complains about database file permissions.

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#57]
When loading a moveit config package (Hydro debian), the following error is thrown due to a database file permissions issue: 

```
[ INFO] [1411442111.897502369]: Loading robot model 'motoman_sia20d'...
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/warehouse_ros/mongo_wrapper_ros.py", line 93, in <module>
    os.makedirs(dbpath)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/ros/hydro/share/motoman_sia20d_moveit_config/default_warehouse_mongo_db'
[mongo_wrapper_ros_ROS_22581_186060070-7] process has died [pid 22719, exit code 1, cmd /opt/ros/hydro/lib/warehouse_ros/mongo_wrapper_ros.py __name:=mongo_wrapper_ros_ROS_22581_186060070 __log:=/home/ros/.ros/log/d31c69b8-42cf-11e4-969f-080027f3243a/mongo_wrapper_ros_ROS_22581_186060070-7.log].
log file: /home/ros/.ros/log/d31c69b8-42cf-11e4-969f-080027f3243a/mongo_wrapper_ros_ROS_22581_186060070-7*.log
[ INFO] [1411442112.415595818]: Publishing maintained planning scene on 'monitored_planning_scene'
```

**Comment by gavanderhoorn** [comment]
Just FYI: I can't reproduce this on Ubuntu 12.04, with `ros-hydro-motoman-sia20d-moveit-config_0.3.3-1precise-20140906-1755-+0000_i386.deb` installed.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: I'm seeing this now too with `ros-hydro-fanuc-lrmate200ic5l-moveit-config 0.3.0-0precise-20150109-0708-+0000` (I suspect other MoveIt config pkgs will show the same). Did you ever figure this out?

**Comment by gavanderhoorn** [comment]
@shaun-edwards: looks like this is caused by a mistake in the `moveit_planning_execution.launch` file. See ros-industrial/fanuc#142.
